baseURL = "https://anto-mathew.github.io/"
languageCode = "en-us"
title = "Anto Mathew"
theme = "PaperMod"
paginate = 5

# PaperMod params
[params]
  author = "ANTO MATHEW"
  tagline = "Senior Software Engineer â€“ PHP | TypeScript | React | DevOps | Microservices"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = false

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/anto-mathew"

  [[params.socialIcons]]
  name = "gitlab"
  url = "https://gitlab.com/users/antomathew18/groups"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/anto-mathew-07264096"

  [[params.socialIcons]]
  name = "docker"
  url = "https://hub.docker.com/u/anto18"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 40
